### PR TITLE
unsafeShift{L,R} -> shift{L,R}

### PR DESCRIPTION
**Pull request by curiousleo**
Context: https://github.com/haskell/random/pull/62/#discussion_r436203356.

### CODE REVIEW

**Review by lehins — APPROVED** [review]
If benchmarks show that there is no change in performance then :+1: from me

**Comment by curiousleo** [comment]
Ah, this is a little tricky:
- The changes in the default implementations of `genWord64` and `uniformWord64` aren't captured by existing benchmarks because SplitMix natively outputs `Word64` and the default implementations aren't used
- We don't have benchmarks for `genShortByteString`

What I have done is to dump the generated assembly with `-O2 -ddump-asm` and it still contains `jmp Data.Bits.shiftL_info`, so at least at this stage, the calls to `shiftL` have not been replaced by calls to `unsafeShiftL`. But I may very well be looking at this the wrong way.

**Comment by curiousleo** [comment]
Looks like I got it confused. `unsafeShiftL` in Haskell code is compiled to `jmp Data.Bits.shiftL_info` in assembly:

Before (using `unsafeShiftL` / `unsafeShiftR`):
```console
$ stack ghc -- -O2 -c src/System/Random/Internal.hs -ddump-asm > Internal-before.asm
$ rg shift Internal-before.asm
11085:	jmp Data.Bits.shiftR_info
11307:	jmp Data.Bits.shiftL_info
11531:	jmp Data.Bits.shiftR_info
11726:	jmp Data.Bits.shiftL_info
31195:	jmp Data.Bits.shiftR_info
35086:	jmp Data.Bits.shiftR_info
35948:	jmp Data.Bits.shiftR_info
```

After (using `shiftL` / `shiftR`):
```console
$ stack ghc -- -O2 -c src/System/Random/Internal.hs -ddump-asm > Internal-after.asm
$ rg shift Internal-after.asm
11085:	jmp Data.Bits.shiftR_info
11307:	jmp Data.Bits.shiftL_info
11531:	jmp Data.Bits.shiftR_info
11726:	jmp Data.Bits.shiftL_info
31195:	jmp Data.Bits.shiftR_info
35086:	jmp Data.Bits.shiftR_info
35948:	jmp Data.Bits.shiftR_info
```

The assembly is the same, modulo some renames. Even the line numbers in the output are the same. I think this shows pretty conclusively that GHC has correctly compiled away the boundary checks performed by `shiftL` and `shiftR`.

**Comment by lehins** [comment]
> We don't have benchmarks for genShortByteString

@curiousleo 
I did add these, remember:
https://github.com/idontgetoutmuch/random/blob/8f48f6ce55f017eb7e5f4f75380189e33eb886cd/bench/Main.hs#L180-L184

**Comment by lehins** [comment]
> The assembly is the same, modulo some renames

Perfect!

**Comment by curiousleo** [comment]
> I did add these, remember

Oops! Thanks. Benchmarked it, no significant difference.

**Review by idontgetoutmuch — APPROVED** [review]

**Pull request merged**
