### PR TITLE
Switch global StdGen to MutVar. Get rid of MutGen in favor of MutVar

### PR DESCRIPTION
**Pull request by lehins**
After giving it some more that I don't think there is much need for `MutGen` wrapper around `MutVar`. But I do not feel to strongly one way or another.

This also implements StdGen using MutVar instead of an IORef. Also something I don't particularly care about, but wanted to give it a shot anyways.

Depends on #57

### CODE REVIEW

**Comment by curiousleo** [comment]
> This also implements StdGen using MutVar instead of an IORef. Also something I don't particularly care about, but wanted to give it a shot anyways.

Are `MutVar` operations generally faster than `IORef` operations?

**Comment by lehins** [comment]
> Are MutVar operations generally faster than IORef operations?

Not at all. They are both backed by `MutVar#` primitive. So there should be no change in performance in this PR.

**Comment by curiousleo** [comment]
It is not 100% clear to me what the consequences of this are from the user perspective.

This looks like a simplification though, so I'm leaning in favour of this change.

**Review by curiousleo — APPROVED** [review]

**Comment by lehins** [comment]
After giving this a bit of thought. I think it might be a bad idea to expose the internals.

If it is ever decided that underlying data type for mutable variable needs to be changed from `MutVar` to something else, it will be a breaking change.

**Pull request closed without merging**
