### PR TITLE
Old ghc benchmarks

### PR DESCRIPTION
**Pull request by lehins**
Get benchmarks to compile with older ghc and change the version from 1.2 to 1.2.0

### CODE REVIEW

**Comment by curiousleo** [comment]
Thanks for doing this! Quick sanity check: have you run the benchmarks with those changes?

**Comment by lehins** [comment]
@curiousleo Yeah, I did. It doesn't seem like the changes here made any difference.

**Review by curiousleo — APPROVED** [review]
Thank you @lehins!

**Comment by curiousleo** [comment]
The Travis integration is broken, but this PR passed: https://travis-ci.org/github/idontgetoutmuch/random/builds/696359393 - let's merge.

**Pull request merged**
